import type { Metadata } from "next";
import { LegalPage, List, Section } from "@/components/legal/legal-page";
import { legal } from "@/lib/legal";
import { createMetadata } from "@/lib/metadata";

export const metadata: Metadata = createMetadata(
  "AI Policy",
  "How model output behaves on Cheela, and who is responsible for it.",
  { path: "/ai-policy" },
);

export default function AiPolicyPage() {
  return (
    <LegalPage
      description="How model output behaves, and who is responsible for it."
      slug="ai-policy"
      title="AI Policy"
    >
      <Section id="what" title="What Cheela does">
        <p>
          Cheela runs an agent loop: it sends your messages and your capability
          manifest to a language model, dispatches the tool calls the model
          returns to your HTTPS endpoint, feeds the results back, and repeats
          until the model answers or the step budget runs out.
        </p>
        <p>
          <strong>We do not train models</strong>, and we do not use your data
          to train anyone else&rsquo;s. Model access runs on our own provider
          credential, which is why you never hand us a third-party API key.
        </p>
      </Section>

      <Section id="generated-content" title="1. AI-generated content">
        <p>
          Output is generated by a statistical model. It is not reviewed by a
          person before it reaches you, and it is not checked for accuracy by
          us. Two identical requests may produce different answers.
        </p>
      </Section>

      <Section id="hallucinations" title="2. Hallucinations and accuracy">
        <p>
          Language models produce confident text that is sometimes wrong. They
          invent citations, misstate facts, produce code that does not compile,
          and call tools with arguments that make no sense. This is a property
          of the technology, not a defect we can remove.
        </p>
        <p>
          <strong>
            Do not rely on model output for anything consequential without a
            human checking it.
          </strong>{" "}
          That applies with particular force to medical, legal, financial and
          safety-critical uses.
        </p>
      </Section>

      <Section id="responsibilities" title="3. Your responsibilities">
        <List
          items={[
            "Review output before acting on it, publishing it, or showing it to your own users as fact.",
            "Disclose to your users that they are interacting with an AI system where they would otherwise reasonably assume a human.",
            "Design your capabilities defensively. The model chooses which to call and with what arguments — a capability that deletes data or spends money on the model's say-so will eventually do so wrongly.",
            "Validate capability inputs at your endpoint. Requests are signed so you can verify they came from us, but we do not verify that the model's arguments make sense.",
            "Comply with the disclosure rules that apply to you. Several jurisdictions now require AI-generated content to be labelled.",
          ]}
        />
      </Section>

      <Section id="restricted" title="4. Restricted uses">
        <p>
          The Acceptable Use Policy governs what you may not do. In addition, do
          not use the service as the sole decision-maker for:
        </p>
        <List
          items={[
            "Medical diagnosis or treatment.",
            "Legal advice presented to a third party as authoritative.",
            "Credit, insurance, employment or housing decisions about an individual.",
            "Anything where a wrong answer causes physical harm.",
          ]}
        />
        <p>
          A person must be accountable for the decision in each of these. Using
          the model to draft, summarise or research is fine; letting it decide
          is not.
        </p>
      </Section>

      <Section id="third-party-models" title="5. Third-party models">
        <p>
          Inference is provided by third parties through OpenRouter. The
          specific model is chosen by us and may change — we select it for
          capability, cost and availability, and we do not guarantee any
          particular model will remain in use.
        </p>
        <p>
          Your messages are transmitted to those providers to produce a
          response. Their handling of that data is governed by their terms,
          which is why they are named as processors in the Privacy Policy. We do
          not control their safety filters, and content they refuse to generate
          will be refused regardless of what this policy permits.
        </p>
      </Section>

      <Section id="ownership" title="6. Content ownership">
        <p>
          <strong>As between you and us, you own the output</strong> your
          executions produce, and you own the input you send. We claim no
          ownership of either.
        </p>
        <p>
          Two limits worth stating plainly. Model output may not be
          copyrightable in some jurisdictions, and we make no representation
          that it is. And a model can produce text closely resembling its
          training data, so we cannot warrant that output is free of third-party
          rights — checking that is your responsibility before you publish or
          sell it.
        </p>
      </Section>

      <Section id="retention" title="7. What we keep">
        <p>
          Message content is not stored. An execution&rsquo;s trace records the
          turn structure of the conversation and nothing anybody wrote.
          Capability inputs and outputs are stored so you can debug a
          capability, and those often contain user text rephrased. The Privacy
          Policy sets this out in full.
        </p>
      </Section>

      <Section id="contact" title="8. Questions">
        <p>
          Write to{" "}
          <a href={`mailto:${legal.contact.general}`}>
            {legal.contact.general}
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
